<template>
   <scroll class="content" :probeType='3' :pullingUp='true' @scroll='scroll' @pullingUp='pulling' ref="scroll">
      <ul>
        <li>哈哈</li>
        <li>哈哈</li>
        <li>哈哈</li>
        <li>哈哈</li>
        <li>哈哈</li>
        <li>哈哈</li>
        <li>哈哈</li>
        <li>哈哈</li>
        <li>哈哈</li>
        <li>哈哈</li>
        <li>哈哈</li>
        <li>哈哈</li>
        <li>哈哈</li>
        <li>哈哈</li>
        <li>哈哈</li>
        <li>哈哈</li>
        <li>哈哈</li>
        <li>哈哈</li>
        <li>哈哈</li>
        <li>哈哈</li>
        <li>哈哈</li>
        <li>哈哈</li>
        <li>哈哈</li>
        <li>哈哈</li>
        <li>哈哈</li>
        <li>哈哈</li>
        <li>哈哈</li>
        <li>哈哈</li>
        <li>哈哈</li>
        <li>哈哈</li>
        <li>哈哈</li>
        <li>哈哈</li>
        <li>哈哈</li>
        <li>哈哈</li>
        <li>哈哈</li>
        <li>哈哈</li>
        <li>哈哈</li>
        <li>哈哈</li>
        <li>哈哈</li>
        <li>哈哈</li>
        <li>哈哈</li>
        <li>哈哈</li>
        <li>哈哈</li>
        <li>哈哈</li>
        <li>哈哈</li>
        <li>哈哈</li>
        <li>哈哈</li>
        <li>哈哈</li>
        <li>哈哈</li>
        <li>哈哈</li>
        <li>哈哈</li>
        <li>哈哈</li>
        <li>哈哈</li>
        <li>哈哈</li>
        <li>哈哈</li>
        <li>哈哈</li>
        <li>哈哈</li>
        <li>哈哈</li>
        <li>哈哈</li>
        <li>哈哈</li>
        <li>哈哈</li>
        <li>哈哈</li>
        <li>哈哈</li>
        <li>哈哈</li>
        <li>哈哈</li>
        <li>哈哈</li>
        <li>哈哈</li>
        <li>哈哈</li>
        <li>哈哈</li>
        <li>哈哈</li>
        <li>哈哈</li>
        <li>哈哈</li>
        <li>哈哈</li>
        <li>哈哈</li>
        <li>哈哈</li>
        <li>哈哈</li>
        <li>哈哈</li>
        <li>哈哈</li>
        <li>哈哈</li>
        <li>哈哈</li>
        <li>哈哈</li>
        <li>哈哈</li>
        <li>哈哈</li>
        <li>哈哈</li>
        <li>哈哈</li>
        <li>哈哈</li>
        <li>哈哈</li>
        <li>哈哈</li>
        <li>哈哈</li>
        <li>哈哈</li>
        <li>哈哈</li>
        <li>哈哈</li>
        <li>哈哈</li>
        <li>哈哈</li>
        <li>哈哈</li>
        <li>哈哈</li>
        <li>哈哈</li>
        <li>哈哈</li>
        <li>哈哈</li>
        <li>哈哈</li>
      </ul>
      <button @click="toto">还好</button>
   </scroll>

</template>

<script>
import scroll from 'components/common/scroll/BScroll'
export default {
  components:{
    scroll
  },
  props:{},
  data(){
    return {
    }
  },
  mounted() {
  },
  methods: {
    scroll(position){
    },
    pulling(){
      console.log('上垃圾');
    },
    toto(){
      this.$refs.scroll.scrollTo(0,0)
    }
  },
}
</script>
<style scoped>
.content{
  height: 150px;
  overflow: hidden;
}
</style>